pipeline {

  agent any

  envoirnment {

   image = "dockerhbuser/myapp :${build_number}"

   stages { 

      stage ('checkout') {
         steps { 

              git branch = 'main'
              URL ='https//github.com/jenkin_project_o1/github.com'
              user id = 'kashwin777'

         }
      }


      stage ('build') {

        steps { 

        sh mvn clean pakages 
      }
   }

       stage ('code_quality') {
         steps { 
                 with sonarqube env ('sonarqube-server')
                 sonar = sonar 
         }
       }


       stage ('docker build') {

          steps {

            docker build -t { 'kashwin777/jenkin_project_o1_demo:03'}
          }
       }

        stage ('docker push') {
          steps { 

          with credentials { [username password (credential id :docker hub_creds, password variable:kashwin@22) ]}
          sh echo password echo pass $ docker login -u , user -- password-stdin }
        }
       }

       stage ('deploy') {

         steps {

           sh kubectl apply -f deployment.yaml
         }
       }
   }


